export enum AdvanceId {
  AdvancedFlight = 'advancedflight',
  Alphabet = 'alphabet',
  Astronomy = 'astronomy',
  AtomicTheory = 'atomictheory',
  Automobile = 'automobile',
  Banking = 'banking',
  BridgeBuilding = 'bridgebuilding',
  BronzeWorking = 'bronzeworking',
  CeremonialBurial = 'ceremonialburial',
  Chemestry = 'chemestry',
  Chivalry = 'chivalry',
  CodeOfLaws = 'codeoflaws',
  Combustion = 'combustion',
  Communism = 'communism',
  Computers = 'computers',
  Conscription = 'conscription',
  Construction = 'construction',
  Currency = 'currency',
  Democracy = 'democracy',
  Electricity = 'electricity',
  Electronics = 'electronics',
  Engineering = 'engineering',
  Explosives = 'explosives',
  Feudalism = 'feudalism',
  Flight = 'flight',
  FusionPower = 'fusionpower',
  GeneticEngineering = 'geneticengineering',
  Gunpowder = 'gunpowder',
  HorsebackRiding = 'horsebackriding',
  Industrialization = 'industrialization',
  Invention = 'invention',
  IronWorking = 'ironworking',
  LaborUnion = 'laborunion',
  Literacy = 'literacy',
  Magnatism = 'magnatism',
  MapMaking = 'mapmaking',
  Masonry = 'masonry',
  MassProduction = 'massproduction',
  Mathematics = 'mathematics',
  Medicine = 'medicine',
  Metallurgy = 'metallurgy',
  Monarchy = 'monarchy',
  Mysticism = 'mysticism',
  Navigation = 'nagivation',
  NuclearFission = 'nuclearfission',
  NuclearPower = 'nuclearpower',
  Philosophy = 'philosophy',
  Physics = 'physics',
  Plastics = 'plastics',
  Pottery = 'pottery',
  RailRoad = 'railroad',
  Recycling = 'recycling',
  Refining = 'refining',
  Religion = 'religion',
  Robotics = 'robotics',
  Rocketry = 'rocketry',
  SpaceFlight = 'spaceflight',
  SteamEngine = 'steamengine',
  Steel = 'steel',
  SuperConductor = 'supeconductor',
  TheCorporation = 'thecorporation',
  TheRepublic = 'therepublic',
  TheWheel = 'thewheel',
  TheoryOfGravity = 'theoryofgravity',
  Trade = 'trade',
  University = 'university',
  Writing = 'writing',
}

export type Advance = {
  prerequisite?: AdvanceId[];
  name: string;
};

export const advances: Record<AdvanceId, Advance> = {
  [AdvanceId.AdvancedFlight]: { name: 'Advanced Flight', prerequisite: [AdvanceId.Flight, AdvanceId.Electricity] },
  [AdvanceId.Alphabet]: { name: 'Alphabet' },
  [AdvanceId.Astronomy]: { name: 'Astronomy', prerequisite: [AdvanceId.Mysticism, AdvanceId.Mathematics] },
  [AdvanceId.AtomicTheory]: { name: 'Atomic Theory', prerequisite: [AdvanceId.TheoryOfGravity, AdvanceId.Physics] },
  [AdvanceId.Automobile]: { name: 'Automobile', prerequisite: [AdvanceId.Combustion, AdvanceId.Steel] },
  [AdvanceId.Banking]: { name: 'Banking', prerequisite: [AdvanceId.TheRepublic, AdvanceId.Trade] },
  [AdvanceId.BridgeBuilding]: {
    name: 'Bridge Building',
    prerequisite: [AdvanceId.Construction, AdvanceId.IronWorking],
  },
  [AdvanceId.BronzeWorking]: { name: 'Bronze Working' },
  [AdvanceId.CeremonialBurial]: { name: 'Ceremonial Burial' },
  [AdvanceId.Chemestry]: { name: 'Chemestry', prerequisite: [AdvanceId.University, AdvanceId.Medicine] },
  [AdvanceId.Chivalry]: { name: 'Chivalry', prerequisite: [AdvanceId.Feudalism, AdvanceId.HorsebackRiding] },
  [AdvanceId.CodeOfLaws]: { name: 'Code of Laws', prerequisite: [AdvanceId.Alphabet] },
  [AdvanceId.Combustion]: { name: 'Combustion', prerequisite: [AdvanceId.Refining, AdvanceId.Explosives] },
  [AdvanceId.Communism]: { name: 'Communism', prerequisite: [AdvanceId.Philosophy, AdvanceId.Industrialization] },
  [AdvanceId.Computers]: { name: 'Computers', prerequisite: [AdvanceId.Mathematics, AdvanceId.Electronics] },
  [AdvanceId.Conscription]: { name: 'Conscription', prerequisite: [AdvanceId.TheRepublic, AdvanceId.Explosives] },
  [AdvanceId.Construction]: { name: 'Construction', prerequisite: [AdvanceId.Masonry, AdvanceId.Currency] },
  [AdvanceId.Currency]: { name: 'Currency', prerequisite: [AdvanceId.BronzeWorking] },
  [AdvanceId.Democracy]: { name: 'Democracy', prerequisite: [AdvanceId.Philosophy, AdvanceId.Literacy] },
  [AdvanceId.Electricity]: { name: 'Electricity', prerequisite: [AdvanceId.Magnatism, AdvanceId.Metallurgy] },
  [AdvanceId.Electronics]: { name: 'Electronics', prerequisite: [AdvanceId.Electricity] },
  [AdvanceId.Engineering]: { name: 'Engineering', prerequisite: [AdvanceId.TheWheel, AdvanceId.Construction] },
  [AdvanceId.Explosives]: { name: 'Explosives', prerequisite: [AdvanceId.Gunpowder, AdvanceId.Chemestry] },
  [AdvanceId.Feudalism]: { name: 'Feudalism', prerequisite: [AdvanceId.Masonry, AdvanceId.Monarchy] },
  [AdvanceId.Flight]: { name: 'Flight', prerequisite: [AdvanceId.Combustion, AdvanceId.Physics] },
  [AdvanceId.FusionPower]: { name: 'Fusionpower', prerequisite: [AdvanceId.NuclearPower, AdvanceId.SuperConductor] },
  [AdvanceId.GeneticEngineering]: {
    name: 'Genetic Engineering',
    prerequisite: [AdvanceId.Medicine, AdvanceId.TheCorporation],
  },
  [AdvanceId.Gunpowder]: { name: 'Gunpowder', prerequisite: [AdvanceId.Invention, AdvanceId.IronWorking] },
  [AdvanceId.HorsebackRiding]: { name: 'Horseback Riding' },
  [AdvanceId.Industrialization]: { name: 'Industrialization', prerequisite: [AdvanceId.RailRoad, AdvanceId.Banking] },
  [AdvanceId.Invention]: { name: 'Invention', prerequisite: [AdvanceId.Engineering, AdvanceId.Literacy] },
  [AdvanceId.IronWorking]: { name: 'Iron Working', prerequisite: [AdvanceId.BronzeWorking] },
  [AdvanceId.LaborUnion]: { name: 'Labor Union', prerequisite: [AdvanceId.MassProduction, AdvanceId.Communism] },
  [AdvanceId.Literacy]: { name: 'Literacy', prerequisite: [AdvanceId.Writing, AdvanceId.CodeOfLaws] },
  [AdvanceId.Magnatism]: { name: 'Magnatism', prerequisite: [AdvanceId.Navigation, AdvanceId.Physics] },
  [AdvanceId.MapMaking]: { name: 'Map Making', prerequisite: [AdvanceId.Alphabet] },
  [AdvanceId.Masonry]: { name: 'Masonry' },
  [AdvanceId.MassProduction]: {
    name: 'Mass Production',
    prerequisite: [AdvanceId.Automobile, AdvanceId.TheCorporation],
  },
  [AdvanceId.Mathematics]: { name: 'Mathematics', prerequisite: [AdvanceId.Alphabet, AdvanceId.Masonry] },
  [AdvanceId.Medicine]: { name: 'Medicine', prerequisite: [AdvanceId.Philosophy, AdvanceId.Trade] },
  [AdvanceId.Metallurgy]: { name: 'Metallurgy', prerequisite: [AdvanceId.Gunpowder, AdvanceId.University] },
  [AdvanceId.Monarchy]: { name: 'Monarchy', prerequisite: [AdvanceId.CeremonialBurial, AdvanceId.CodeOfLaws] },
  [AdvanceId.Mysticism]: { name: 'Mysticism', prerequisite: [AdvanceId.CeremonialBurial] },
  [AdvanceId.Navigation]: { name: 'Nagivation', prerequisite: [AdvanceId.MapMaking, AdvanceId.Astronomy] },
  [AdvanceId.NuclearFission]: {
    name: 'Nuclear Fission',
    prerequisite: [AdvanceId.MassProduction, AdvanceId.AtomicTheory],
  },
  [AdvanceId.NuclearPower]: { name: 'Nuclear Power', prerequisite: [AdvanceId.NuclearFission, AdvanceId.Electronics] },
  [AdvanceId.Philosophy]: { name: 'Philosophy', prerequisite: [AdvanceId.Mysticism, AdvanceId.Literacy] },
  [AdvanceId.Physics]: { name: 'Physics', prerequisite: [AdvanceId.Mathematics, AdvanceId.Navigation] },
  [AdvanceId.Plastics]: { name: 'Plastics', prerequisite: [AdvanceId.Refining, AdvanceId.SpaceFlight] },
  [AdvanceId.Pottery]: { name: 'Pottery' },
  [AdvanceId.RailRoad]: { name: 'RailRoad', prerequisite: [AdvanceId.SteamEngine, AdvanceId.BridgeBuilding] },
  [AdvanceId.Recycling]: { name: 'Recycling', prerequisite: [AdvanceId.MassProduction, AdvanceId.Democracy] },
  [AdvanceId.Refining]: { name: 'Refining', prerequisite: [AdvanceId.Chemestry, AdvanceId.TheCorporation] },
  [AdvanceId.Religion]: { name: 'Religion', prerequisite: [AdvanceId.Philosophy, AdvanceId.Writing] },
  [AdvanceId.Robotics]: { name: 'Robotics', prerequisite: [AdvanceId.Plastics, AdvanceId.Computers] },
  [AdvanceId.Rocketry]: { name: 'Rocketry', prerequisite: [AdvanceId.AdvancedFlight, AdvanceId.Electronics] },
  [AdvanceId.SpaceFlight]: { name: 'Space Flight', prerequisite: [AdvanceId.Computers, AdvanceId.Rocketry] },
  [AdvanceId.SteamEngine]: { name: 'Steam Engine', prerequisite: [AdvanceId.Physics, AdvanceId.Invention] },
  [AdvanceId.Steel]: { name: 'Steel', prerequisite: [AdvanceId.Metallurgy, AdvanceId.Industrialization] },
  [AdvanceId.SuperConductor]: { name: 'Supe Conductor', prerequisite: [AdvanceId.Plastics, AdvanceId.MassProduction] },
  [AdvanceId.TheCorporation]: {
    name: 'The Corporation',
    prerequisite: [AdvanceId.Banking, AdvanceId.Industrialization],
  },
  [AdvanceId.TheRepublic]: { name: 'The Republic', prerequisite: [AdvanceId.CodeOfLaws, AdvanceId.Literacy] },
  [AdvanceId.TheWheel]: { name: 'The Wheel' },
  [AdvanceId.TheoryOfGravity]: { name: 'Theory of Gravity', prerequisite: [AdvanceId.Astronomy, AdvanceId.University] },
  [AdvanceId.Trade]: { name: 'Trade', prerequisite: [AdvanceId.Currency, AdvanceId.CodeOfLaws] },
  [AdvanceId.University]: { name: 'University', prerequisite: [AdvanceId.Mathematics, AdvanceId.Philosophy] },
  [AdvanceId.Writing]: { name: 'Writing', prerequisite: [AdvanceId.Alphabet] },
};
