export enum GameAction {
  UnitMoveNorth = "UnitMoveNorth",
  UnitMoveNorthEast = "UnitMoveNorthEast",
  UnitMoveEast = "UnitMoveEast",
  UnitMoveSouthEast = "UnitMoveSouthEast",
  UnitMoveSouth = "UnitMoveSouth",
  UnitMoveSouthWest = "UnitMoveSouthWest",
  UnitMoveWest = "UnitMoveWest",
  UnitMoveNorthWest = "UnitMoveNorthWest",
  UnitNoOrders = "UnitNoOrders",
  EndTurn = "EndTurn",
  Center = "Center",
}

export const keyboardMapping: Record<string, GameAction | undefined> = {
  ArrowUp: GameAction.UnitMoveNorth,
  ArrowRight: GameAction.UnitMoveEast,
  ArrowDown: GameAction.UnitMoveSouth,
  ArrowLeft: GameAction.UnitMoveWest,
  Numpad8: GameAction.UnitMoveNorth,
  Numpad9: GameAction.UnitMoveNorthEast,
  Numpad6: GameAction.UnitMoveEast,
  Numpad3: GameAction.UnitMoveSouthEast,
  Numpad2: GameAction.UnitMoveSouth,
  Numpad1: GameAction.UnitMoveSouthWest,
  Numpad4: GameAction.UnitMoveWest,
  Numpad7: GameAction.UnitMoveNorthWest,
  Space: GameAction.UnitNoOrders,
  NumpadEnter: GameAction.EndTurn,
  Enter: GameAction.EndTurn,
  KeyC: GameAction.Center,
};
