export enum Keys {
  ArrowUp = 'ArrowUp',
  ArrowRight = 'ArrowRight',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  Enter = 'Enter',
  Escape = 'Escape',
  KeyB = 'KeyB',
  KeyC = 'KeyC',
  KeyF = 'KeyF',
  KeyI = 'KeyI',
  KeyM = 'KeyM',
  KeyR = 'KeyR',
  KeyW = 'KeyW',
  Numpad1 = 'Numpad1',
  Numpad2 = 'Numpad2',
  Numpad3 = 'Numpad3',
  Numpad4 = 'Numpad4',
  Numpad5 = 'Numpad5',
  Numpad6 = 'Numpad6',
  Numpad7 = 'Numpad7',
  Numpad8 = 'Numpad8',
  Numpad9 = 'Numpad9',
  NumpadEnter = 'NumpadEnter',
  Space = 'Space',
}
